// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0dB043MPcJDKDqq_Uf-jJUuQK2mjXiI',
    appId: '1:267118373830:web:92f8d9bd8f965312fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    authDomain: 'fans-food-stf.firebaseapp.com',
    storageBucket: 'fans-food-stf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0dB043MPcJDKDqq_Uf-jJUuQK2mjXiI',
    appId: '1:267118373830:android:92f8d9bd8f965312fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    storageBucket: 'fans-food-stf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvPXXbqn-E6J91XrecuWXK9eJn9r4_Q8',
    appId: '1:267118373830:ios:63ef08f0702a7a63fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    storageBucket: 'fans-food-stf.firebasestorage.app',
    iosBundleId: 'com.fansfood',
  );
}
